apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-echoserver
  namespace: kubechecks
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: development
        values:
          url: https://kubernetes.default.svc
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      name: "in-cluster-echo-server-{{ metadata.labels.environment }}"
      namespace: kubechecks
      labels:
        argocd.argoproj.io/application-set-name: "app-set-echoserver"
    spec:
      destination:
        namespace: "echo-server-{{ metadata.labels.environment }}"
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/Greyeye/sincere-chimp
        targetRevision: HEAD
        path: 'apps/app-set-echo-server/'
        helm:
          valueFiles:
            - values.yaml
            - values-{{ metadata.labels.environment }}.yaml
          ignoreMissingValueFiles: true
          values: |-
            ingress:
              enabled: false
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      sources: []
